#!/bin/bash
# install.sh — lfun-team-pipeline installer
# Installs agents, templates, and the `team` CLI command.
#
# Usage:
#   bash install.sh              # normal install
#   bash install.sh --update     # update existing installation

set -euo pipefail

VERSION="6.5"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_SRC="$REPO_DIR/agents"
AGENTS_DST="$HOME/.claude/agents"
TEMPLATES_DST="$HOME/.local/share/team-pipeline"
BIN_DIR="$HOME/.local/bin"
TEAM_CMD="$BIN_DIR/team"

UPDATE_MODE="${1:-}"

print_header() {
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║       lfun-team-pipeline  v${VERSION}  installer        ║"
  echo "║       Claude Code Multi-Agent Delivery Pipeline      ║"
  echo "╚══════════════════════════════════════════════════════╝"
  echo ""
}

print_header

# ── 1. Install agents to ~/.claude/agents/ ──────────────────────────
echo "▶ Step 1/4 — Installing agents to $AGENTS_DST"

if [ ! -d "$AGENTS_SRC" ]; then
  echo "  ❌ agents/ directory not found. Run this script from the repo root."
  exit 1
fi

mkdir -p "$AGENTS_DST"

EXISTING=$(find "$AGENTS_DST" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l)
if [ "$EXISTING" -gt 0 ] && [ "$UPDATE_MODE" != "--update" ]; then
  BACKUP_DIR="$AGENTS_DST.backup.$(date +%Y%m%d%H%M%S)"
  echo "  ⚠  Backing up $EXISTING existing agents → $BACKUP_DIR"
  cp -r "$AGENTS_DST" "$BACKUP_DIR"
fi

INSTALLED=0
while IFS= read -r f; do
  cp "$f" "$AGENTS_DST/$(basename "$f")"
  INSTALLED=$((INSTALLED + 1))
done < <(find "$AGENTS_SRC" -maxdepth 1 -name "*.md" | sort)

echo "  ✓ $INSTALLED agents installed"

# ── 2. Copy templates to ~/.local/share/team-pipeline/ ──────────────
echo ""
echo "▶ Step 2/4 — Installing templates to $TEMPLATES_DST"

mkdir -p "$TEMPLATES_DST"
cp -r "$REPO_DIR/templates/." "$TEMPLATES_DST/"
echo "  ✓ Pipeline templates installed"

# ── 3. Install `team` CLI to ~/.local/bin/ ───────────────────────────
echo ""
echo "▶ Step 3/4 — Installing \`team\` command to $BIN_DIR"

mkdir -p "$BIN_DIR"
cat > "$TEAM_CMD" << 'TEAM_SCRIPT'
#!/bin/bash
# team — lfun-team-pipeline CLI
set -euo pipefail

VERSION="6.5"
TEAM_HOME="$HOME/.local/share/team-pipeline"

usage() {
  echo ""
  echo "  lfun-team-pipeline v${VERSION}"
  echo ""
  echo "  Usage: team <command>"
  echo ""
  echo "  Commands:"
  echo "    init      Initialize pipeline in the current project directory"
  echo "    status    Show current pipeline execution progress"
  echo "    upgrade   Upgrade playbook + autosteps in-place (preserves state)"
  echo "    version   Print version"
  echo "    replan    Re-plan the proposal queue (keeps completed work)"
  echo "    run       Auto-run pipeline batches until done or intervention needed"
  echo "    scan      Scan codebase for components and detect duplicates"
  echo "    update    Re-run installer to update agents and templates"
  echo ""
  echo "  Examples:"
  echo "    cd my-project && team init"
  echo "    team run"
  echo "    team status"
  echo ""
}

cmd_init() {
  if [ ! -d "$TEAM_HOME/.pipeline" ]; then
    echo "❌ Team pipeline not installed. Run: bash install.sh"
    exit 1
  fi

  echo ""
  echo "  Initializing lfun-team-pipeline in: $(pwd)"
  echo ""

  # Create directory structure
  mkdir -p .pipeline/autosteps .pipeline/artifacts .pipeline/history

  # Copy config
  if [ -f ".pipeline/config.json" ]; then
    echo "  ⚠  .pipeline/config.json already exists, skipping"
  else
    cp "$TEAM_HOME/.pipeline/config.json" .pipeline/config.json
    echo "  ✓ .pipeline/config.json"
  fi

  # Copy playbook
  cp "$TEAM_HOME/.pipeline/playbook.md" .pipeline/playbook.md
  echo "  ✓ .pipeline/playbook.md"

  # Copy project-memory template (only if not exists, preserve user data)
  if [ -f ".pipeline/project-memory.json" ]; then
    echo "  ⚠  .pipeline/project-memory.json already exists, skipping"
  else
    cp "$TEAM_HOME/.pipeline/project-memory.json" .pipeline/project-memory.json
    echo "  ✓ .pipeline/project-memory.json"
  fi

  # Note: proposal-queue.json is NOT copied here.
  # It is generated by System Planning (first run of `claude --agent pilot`).
  # Copying an empty template would bypass System Planning and cause immediate ALL-COMPLETED.

  # Copy autosteps
  STEP_COUNT=0
  while IFS= read -r f; do
    dest=".pipeline/autosteps/$(basename "$f")"
    cp "$f" "$dest"
    STEP_COUNT=$((STEP_COUNT + 1))
  done < <(find "$TEAM_HOME/.pipeline/autosteps" \( -name "*.sh" -o -name "*.py" \) | sort)
  echo "  ✓ .pipeline/autosteps/ ($STEP_COUNT scripts)"

  # Copy llm-router.sh
  if [ -f "$TEAM_HOME/.pipeline/llm-router.sh" ]; then
    cp "$TEAM_HOME/.pipeline/llm-router.sh" .pipeline/llm-router.sh
    chmod +x .pipeline/llm-router.sh
    echo "  ✓ .pipeline/llm-router.sh"
  fi

  # Copy CLAUDE.md
  if [ -f "CLAUDE.md" ]; then
    echo "  ⚠  CLAUDE.md already exists, skipping"
  else
    cp "$TEAM_HOME/CLAUDE.md" CLAUDE.md
    echo "  ✓ CLAUDE.md"
  fi

  echo ""
  echo "  ✅ Pipeline initialized! Next steps:"
  echo ""
  echo "     1. Edit .pipeline/config.json  ← set project_name and tech stack"
  echo "     2. claude --dangerously-skip-permissions --agent pilot ← start the pipeline"
  echo ""
}

cmd_version() {
  echo "lfun-team-pipeline v${VERSION}"
}

cmd_update() {
  echo ""
  echo "  To update, run install.sh from the team-creator git repository:"
  echo ""
  echo "    cd /path/to/team-creator && bash install.sh --update"
  echo ""
  echo "  This ensures agents and templates are copied from the latest source."
  echo ""
}

cmd_upgrade() {
  if [ ! -d "$TEAM_HOME/.pipeline" ]; then
    echo "❌ Team pipeline not installed. Run: bash install.sh"
    exit 1
  fi

  if [ ! -d ".pipeline" ]; then
    echo "❌ No .pipeline/ directory found. Run: team init"
    exit 1
  fi

  echo ""
  echo "  Upgrading lfun-team-pipeline in: $(pwd)"
  echo ""

  # ── Phase 1: Pre-flight — detect if migration is needed ──────────
  MIGRATE_SCRIPT="$TEAM_HOME/scripts/migrate-phase-names.py"
  NEEDS_MIGRATE=false
  if [ -f ".pipeline/config.json" ] && grep -q '"phase-[0-9]' .pipeline/config.json 2>/dev/null; then
    NEEDS_MIGRATE=true
  fi
  if [ -f ".pipeline/state.json" ] && grep -q '"phase-[0-9]' .pipeline/state.json 2>/dev/null; then
    NEEDS_MIGRATE=true
  fi

  # If migration is needed but script is missing, abort early
  if [ "$NEEDS_MIGRATE" = true ] && [ ! -f "$MIGRATE_SCRIPT" ]; then
    echo "  ❌ Phase name migration required but migration script not found."
    echo "     Expected: $MIGRATE_SCRIPT"
    echo ""
    echo "  Fix: Re-run installer first:"
    echo "    cd /path/to/lfun-team-pipeline && bash install.sh --update"
    echo "    cd $(pwd) && team upgrade"
    echo ""
    exit 1
  fi

  # ── Phase 2: Backup config/state (before anything is touched) ────
  BACKUP_TS=$(date +%Y%m%d%H%M%S)
  BACKUP_DIR=".pipeline/.upgrade-backup-${BACKUP_TS}"
  if [ "$NEEDS_MIGRATE" = true ]; then
    mkdir -p "$BACKUP_DIR"
    [ -f ".pipeline/config.json" ] && cp .pipeline/config.json "$BACKUP_DIR/"
    [ -f ".pipeline/state.json" ] && cp .pipeline/state.json "$BACKUP_DIR/"
    echo "  ✓ Backup saved to $BACKUP_DIR"
  fi

  # ── Phase 3: Migrate config/state FIRST (before template upgrade) ──
  #    Order matters: if migration fails, playbook is still old version,
  #    so the project stays consistent and usable.
  if [ "$NEEDS_MIGRATE" = true ]; then
    echo ""
    echo "  Migrating phase names (phase-X → X.semantic-name)..."
    MIGRATE_OK=true

    # Schema migration (execution_log field) — do this before phase rename
    if [ -f ".pipeline/state.json" ]; then
      python3 -c "
import json
s = json.load(open('.pipeline/state.json'))
if 'execution_log' not in s:
    s['execution_log'] = []
    json.dump(s, open('.pipeline/state.json', 'w'), ensure_ascii=False, indent=2)
    print('  ✓ state.json: added execution_log field')
" 2>/dev/null || true
    fi

    # Phase name migration
    if [ -f ".pipeline/config.json" ]; then
      if ! python3 "$MIGRATE_SCRIPT" --migrate-config .pipeline/config.json; then
        echo "  ❌ config.json migration failed"
        MIGRATE_OK=false
      fi
    fi

    if [ "$MIGRATE_OK" = true ] && [ -f ".pipeline/state.json" ]; then
      if ! python3 "$MIGRATE_SCRIPT" --migrate-state .pipeline/state.json; then
        echo "  ❌ state.json migration failed"
        MIGRATE_OK=false
      fi
    fi

    # Verify migration result
    if [ "$MIGRATE_OK" = true ]; then
      VERIFY_FAIL=false
      # Check no old-style names remain
      if [ -f ".pipeline/config.json" ] && grep -q '"phase-[0-9]' .pipeline/config.json 2>/dev/null; then
        echo "  ❌ Old phase names still present in config.json"
        VERIFY_FAIL=true
      fi
      if [ -f ".pipeline/state.json" ] && grep -q '"phase-[0-9]' .pipeline/state.json 2>/dev/null; then
        echo "  ❌ Old phase names still present in state.json"
        VERIFY_FAIL=true
      fi
      # Check valid JSON
      if [ -f ".pipeline/config.json" ] && ! python3 -c "import json; json.load(open('.pipeline/config.json'))" 2>/dev/null; then
        echo "  ❌ config.json is not valid JSON after migration"
        VERIFY_FAIL=true
      fi
      if [ -f ".pipeline/state.json" ] && ! python3 -c "import json; json.load(open('.pipeline/state.json'))" 2>/dev/null; then
        echo "  ❌ state.json is not valid JSON after migration"
        VERIFY_FAIL=true
      fi
      [ "$VERIFY_FAIL" = true ] && MIGRATE_OK=false
    fi

    # Rollback on failure — restore from backup, playbook NOT yet upgraded
    if [ "$MIGRATE_OK" = false ]; then
      echo ""
      echo "  ⚠  Rolling back config.json and state.json from backup..."
      [ -f "$BACKUP_DIR/config.json" ] && cp "$BACKUP_DIR/config.json" .pipeline/config.json
      [ -f "$BACKUP_DIR/state.json" ] && cp "$BACKUP_DIR/state.json" .pipeline/state.json
      echo ""
      echo "  ❌ Upgrade aborted: config/state migration failed, all files restored."
      echo "     Your project is unchanged and still usable with the old version."
      echo ""
      echo "  To retry manually:"
      echo "    python3 $MIGRATE_SCRIPT --migrate-config .pipeline/config.json"
      echo "    python3 $MIGRATE_SCRIPT --migrate-state .pipeline/state.json"
      echo "    team upgrade   # then retry"
      echo ""
      echo "  Backup kept at: $BACKUP_DIR"
      echo ""
      exit 1
    fi

    echo "  ✓ Phase names migrated successfully"
    rm -rf "$BACKUP_DIR"
    echo "  ✓ Backup cleaned up"
  else
    # No migration needed, still add execution_log if missing
    if [ -f ".pipeline/state.json" ]; then
      python3 -c "
import json
s = json.load(open('.pipeline/state.json'))
if 'execution_log' not in s:
    s['execution_log'] = []
    json.dump(s, open('.pipeline/state.json', 'w'), ensure_ascii=False, indent=2)
    print('  ✓ state.json: added execution_log field')
else:
    print('  ✓ state.json: already compatible')
" 2>/dev/null || true
    fi
    echo "  ✓ Phase names: already migrated"
  fi

  # ── Phase 4: Upgrade template files (safe — config/state already migrated) ──
  cp "$TEAM_HOME/.pipeline/playbook.md" .pipeline/playbook.md
  echo "  ✓ .pipeline/playbook.md upgraded"

  for ext in sh py; do cp "$TEAM_HOME/.pipeline/autosteps/"*."$ext" .pipeline/autosteps/ 2>/dev/null || true; done
  AUTOSTEP_COUNT=$(ls .pipeline/autosteps/*.sh .pipeline/autosteps/*.py 2>/dev/null | wc -l)
  echo "  ✓ $AUTOSTEP_COUNT autosteps upgraded"

  if [ -f "$TEAM_HOME/.pipeline/llm-router.sh" ]; then
    cp "$TEAM_HOME/.pipeline/llm-router.sh" .pipeline/llm-router.sh
    chmod +x .pipeline/llm-router.sh
    echo "  ✓ llm-router.sh upgraded"
  fi

  if [ -f "$TEAM_HOME/CLAUDE.md" ]; then
    cp "$TEAM_HOME/CLAUDE.md" CLAUDE.md
    echo "  ✓ CLAUDE.md upgraded"
  fi

  echo ""
  echo "  Preserved (not modified):"
  echo "    .pipeline/project-memory.json"
  echo "    .pipeline/proposal-queue.json"
  echo "    .pipeline/artifacts/*"
  echo ""

  echo "  ✅ Upgraded to v${VERSION}"
  echo ""
  echo "  Run 'claude --dangerously-skip-permissions --agent pilot' to continue from current phase."
  echo ""
}

cmd_replan() {
  if [ ! -f ".pipeline/proposal-queue.json" ]; then
    echo "❌ No proposal queue found. Run: claude --agent pilot"
    exit 1
  fi

  echo ""
  echo "  Re-planning: removing proposal queue to trigger System Planning"
  echo ""

  # Archive current queue
  BACKUP="proposal-queue.backup.$(date +%Y%m%d%H%M%S).json"
  cp .pipeline/proposal-queue.json ".pipeline/$BACKUP" 2>/dev/null || true
  echo "  ✓ Backed up current queue to .pipeline/$BACKUP"

  # Remove queue to trigger re-planning
  rm .pipeline/proposal-queue.json
  echo "  ✓ Queue removed. Next 'claude --agent pilot' will enter System Planning."
  echo ""
  echo "  Note: Completed proposals are preserved in project-memory.json."
  echo "  The new plan will build on existing progress."
  echo ""
}

cmd_status() {
  if [ ! -f ".pipeline/state.json" ]; then
    echo ""
    echo "  ❌ No pipeline found in current directory."
    echo "     Run: team init && claude --dangerously-skip-permissions --agent pilot"
    echo ""
    exit 1
  fi

  python3 - << 'PYEOF'
import json, os, sys
from datetime import datetime, timezone

# ── ANSI colors ────────────────────────────────────────────────────
RESET  = "\033[0m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
GREEN  = "\033[32m"
YELLOW = "\033[33m"
RED    = "\033[31m"
CYAN   = "\033[36m"
BLUE   = "\033[34m"
WHITE  = "\033[37m"

def c(color, text): return f"{color}{text}{RESET}"

# ── Load state.json ────────────────────────────────────────────────
state = json.load(open(".pipeline/state.json"))
project   = state.get("project_name", os.path.basename(os.getcwd()))
phase     = state.get("current_phase", "?")
last_done = state.get("last_completed_phase", "-")
status    = state.get("status", "?")
pipeline_id = state.get("pipeline_id", "-")
cond      = state.get("conditional_agents", {})
attempts  = state.get("attempt_counts", {})

# ── Header ─────────────────────────────────────────────────────────
print()
print(c(BOLD + CYAN, f"  ╔══ Pipeline Status — {project} ══"))
print(c(CYAN,         f"  ║"))

status_color = GREEN if status == "completed" else (YELLOW if status == "running" else RED)
print(c(CYAN, "  ║") + f"  {c(BOLD, 'Pipeline:')}  {pipeline_id}")
print(c(CYAN, "  ║") + f"  {c(BOLD, 'Status:')}    {c(status_color + BOLD, status.upper())}")
print(c(CYAN, "  ║") + f"  {c(BOLD, 'Phase:')}     {c(BOLD, phase)}  {c(DIM, f'(last done: {last_done})')}")

# ── Conditional agents ─────────────────────────────────────────────
if cond:
    active = [k for k, v in cond.items() if v]
    inactive = [k for k, v in cond.items() if not v]
    parts = [c(GREEN, f"+{k}") for k in active] + [c(DIM, f"-{k}") for k in inactive]
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Agents:')}    {', '.join(parts)}")

# ── Proposal queue ─────────────────────────────────────────────────
queue_file = ".pipeline/proposal-queue.json"
if os.path.exists(queue_file):
    q = json.load(open(queue_file))
    proposals = q if isinstance(q, list) else q.get("proposals", [])
    system_name = q.get("system_name", "") if isinstance(q, dict) else ""
    total = len(proposals)
    done  = sum(1 for p in proposals if p.get("status") == "completed")
    running = [p for p in proposals if p.get("status") == "running"]

    print(c(CYAN, "  ║"))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'System:')}    {system_name}")
    bar_filled = int(done / total * 20) if total else 0
    bar = c(GREEN, "█" * bar_filled) + c(DIM, "░" * (20 - bar_filled))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Proposals:')} [{bar}{RESET}] {c(BOLD, str(done))}/{total}")
    print(c(CYAN, "  ║"))

    for p in proposals:
        pid    = p.get("id", "?")
        title  = p.get("title", "")
        pst    = p.get("status", "pending")
        if pst == "completed":
            icon = c(GREEN, "✓")
            color = DIM
        elif pst == "running":
            icon = c(YELLOW + BOLD, "▶")
            color = BOLD
        else:
            icon = c(DIM, "○")
            color = ""
        deps = p.get("depends_on", [])
        dep_str = c(DIM, f"  ← {', '.join(deps)}") if deps else ""
        print(c(CYAN, "  ║") + f"    {icon} {c(color, f'[{pid}] {title}')}{dep_str}")

# ── Step execution log ─────────────────────────────────────────────
index_file = ".pipeline/artifacts/logs/pipeline.index.json"
ex_log = state.get("execution_log", [])

steps = []
if os.path.exists(index_file):
    idx = json.load(open(index_file))
    steps = idx.get("steps", [])
elif ex_log:
    steps = ex_log

if steps:
    print(c(CYAN, "  ║"))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Execution Log:')}  ({len(steps)} steps)")

    RESULT_COLOR = {"PASS": GREEN, "WARN": YELLOW, "FAIL": RED, "SKIP": DIM, "ERROR": RED}

    # Show all steps; mark rollbacks
    for i, s in enumerate(steps):
        step   = s.get("step", "?")
        result = s.get("result", "?")
        attempt = s.get("attempt", 1)
        rollback_to = s.get("caused_rollback_to") or s.get("rollback_to")
        triggered_by = s.get("rollback_triggered_by")

        rc = RESULT_COLOR.get(result, WHITE)
        attempt_str = c(DIM, f" ×{attempt}") if attempt > 1 else ""
        rollback_str = c(YELLOW, f" → rollback to {rollback_to}") if rollback_to else ""
        triggered_str = c(DIM, f" [by {triggered_by}]") if triggered_by else ""

        is_last = (i == len(steps) - 1)
        prefix = c(CYAN, "  ║") + ("  └─" if is_last else "  ├─")
        print(f"{prefix} {c(rc + BOLD, result):>6}  {step}{attempt_str}{rollback_str}{triggered_str}")

# ── Retry counts (phases with >1 attempts) ─────────────────────────
notable = {k: v for k, v in attempts.items() if isinstance(v, int) and v > 1}
if notable:
    print(c(CYAN, "  ║"))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Retried phases:')}")
    for k, v in sorted(notable.items()):
        print(c(CYAN, "  ║") + f"    {c(YELLOW, k)}: {v} attempts")

# ── Footer ─────────────────────────────────────────────────────────
print(c(CYAN, "  ║"))
print(c(BOLD + CYAN, "  ╚" + "═" * 40))
print()
PYEOF
}

cmd_run() {
  if [ ! -d ".pipeline" ]; then
    echo "❌ No .pipeline/ directory found. Run: team init"
    exit 1
  fi

  # Write the PTY runner to a temp file and execute it.
  # Architecture: Python opens a PTY pair, runs claude with the slave end
  # (so claude sees a real terminal and its full TUI works), proxies all
  # I/O between the user's real terminal and the master end, and monitors
  # the output stream for [EXIT].
  # On [EXIT]: terminate the current claude process and start a FRESH one
  # for the next batch — matching the intended `claude --agent pilot`
  # single-batch-then-exit contract described in CLAUDE.md.
  _RUNNER=$(mktemp "${TMPDIR:-/tmp}/team-runner-XXXXXX")
  trap 'rm -f "$_RUNNER"' EXIT

  cat > "$_RUNNER" << 'PYEOF'
#!/usr/bin/env python3
"""
team run — PTY daemon (multi-batch loop)

Each pipeline batch runs as a FRESH `claude --agent pilot` process.
When [EXIT] appears in the output:
  1. The current claude process is terminated.
  2. Pipeline state is checked.
  3. If not done, a new claude process is spawned for the next batch.
"""
import os, sys, select, signal, termios, tty, fcntl, time, json, subprocess

# ── helpers ──────────────────────────────────────────────────────────────────

def get_state():
    try:
        s = json.load(open('.pipeline/state.json'))
        dep = s.get('depend_collector_result', {})
        return s.get('status', 'running'), len(dep.get('unfilled_deps', []))
    except Exception:
        return 'unknown', 0

def resize_pty(master_fd):
    try:
        ws = fcntl.ioctl(sys.stdout.fileno(), termios.TIOCGWINSZ, b'\x00' * 8)
        fcntl.ioctl(master_fd, termios.TIOCSWINSZ, ws)
    except Exception:
        pass

def print_report():
    try:
        G="\033[32m"; Y="\033[33m"; R="\033[31m"; C="\033[36m"; B="\033[1m"; E="\033[0m"
        s = json.load(open('.pipeline/state.json'))
        q = json.load(open('.pipeline/proposal-queue.json')) if os.path.exists('.pipeline/proposal-queue.json') else []
        props = q if isinstance(q, list) else q.get('proposals', [])
        steps = s.get('execution_log', [])
        done  = sum(1 for p in props if p.get('status') == 'completed')
        ps    = sum(1 for e in steps if e.get('result') == 'PASS')
        fs    = sum(1 for e in steps if e.get('result') == 'FAIL')
        ws    = sum(1 for e in steps if e.get('result') == 'WARN')
        lines = [
            f"\r\n{B}{C}  ╔══ Pipeline Final Report ══════════════════════╗{E}",
            f"{C}  ║{E}  {B}Project:{E}    {s.get('project_name', os.path.basename(os.getcwd()))}",
            f"{C}  ║{E}  {B}Proposals:{E}  {G}{done}/{len(props)} completed{E}",
            f"{C}  ║{E}  {B}Steps:{E}      {G}{ps} PASS{E}  {Y}{ws} WARN{E}  {R}{fs} FAIL{E}  (total {len(steps)})",
            f"{C}  ║{E}",
        ]
        for p in props:
            icon = f"{G}✓{E}" if p.get('status') == 'completed' else f"{Y}○{E}"
            lines.append(f"{C}  ║{E}    {icon}  {p.get('title', '')}")
        lines.append(f"{B}{C}  ╚═══════════════════════════════════════════════╝{E}\r\n")
        sys.stdout.buffer.write('\r\n'.join(lines).encode())
        sys.stdout.buffer.flush()
    except Exception as ex:
        sys.stdout.buffer.write(f'\r\n[report error: {ex}]\r\n'.encode())
        sys.stdout.buffer.flush()

def write_status(msg, color=36):
    sys.stdout.buffer.write(f'\r\n\033[{color}m{msg}\033[0m\r\n'.encode())
    sys.stdout.buffer.flush()

# ── main ─────────────────────────────────────────────────────────────────────

def main():
    stdin_fd = sys.stdin.fileno()
    if not os.isatty(stdin_fd):
        sys.stderr.write(
            '\n  ❌  team run requires a real terminal (tty).\n'
            '     Run it directly in your shell, not via a pipe or script.\n\n'
        )
        sys.exit(1)

    # Inherit env without CLAUDECODE so nested invocation is allowed
    env = {k: v for k, v in os.environ.items() if k != 'CLAUDECODE'}
    saved_tty = termios.tcgetattr(stdin_fd)

    def start_claude():
        """Spawn a fresh claude process with its own PTY slave."""
        mfd, sfd = os.openpty()
        resize_pty(mfd)

        def child_setup():
            os.setsid()
            try:
                fcntl.ioctl(0, termios.TIOCSCTTY, 0)
            except Exception:
                pass

        p = subprocess.Popen(
            ['claude', '--dangerously-skip-permissions', '--agent', 'pilot'],
            stdin=sfd, stdout=sfd, stderr=sfd,
            env=env, preexec_fn=child_setup, close_fds=True,
        )
        os.close(sfd)
        return p, mfd

    def kill_claude(p, mfd):
        """Terminate claude and close the master PTY fd."""
        try:
            p.terminate()
            p.wait(timeout=5)
        except Exception:
            try:
                p.kill()
            except Exception:
                pass
        try:
            os.close(mfd)
        except Exception:
            pass

    tty.setraw(stdin_fd)
    batch_num = 0

    try:
        while True:
            batch_num += 1
            proc, master_fd = start_claude()
            signal.signal(signal.SIGWINCH, lambda s, f: resize_pty(master_fd))

            buf          = b''
            exit_count   = 0
            prompt_sent  = False
            t0           = time.monotonic()
            t_last_out   = t0
            exit_seen_at = None

            # ── Run this batch until [EXIT] or natural claude exit ────────────
            while proc.poll() is None:
                try:
                    r, _, _ = select.select([master_fd, stdin_fd], [], [], 0.2)
                except (select.error, ValueError):
                    break

                now = time.monotonic()

                # Send initial prompt after settling (2 s silence or 5 s absolute)
                if not prompt_sent and (
                    (now - t_last_out > 2.0 and now - t0 > 1.0) or now - t0 > 5.0
                ):
                    os.write(master_fd, '请执行下一批次\r'.encode())
                    prompt_sent = True

                # [EXIT] detected and settled for 2 s → end this batch
                if exit_seen_at is not None and now - exit_seen_at >= 2.0:
                    break

                for fd in r:
                    if fd == master_fd:
                        try:
                            data = os.read(master_fd, 4096)
                        except OSError:
                            break
                        os.write(sys.stdout.fileno(), data)
                        buf += data
                        t_last_out = time.monotonic()

                        new_count = buf.count(b'[EXIT]')
                        if new_count > exit_count:
                            exit_count   = new_count
                            exit_seen_at = time.monotonic()

                    elif fd == stdin_fd:
                        try:
                            data = os.read(stdin_fd, 1024)
                        except OSError:
                            break
                        if data:
                            os.write(master_fd, data)

            # ── Terminate this claude instance ────────────────────────────────
            kill_claude(proc, master_fd)

            # ── Check pipeline state and decide what to do next ───────────────
            st, unfilled = get_state()

            if st == 'ALL-COMPLETED':
                print_report()
                break
            elif st == 'escalation':
                write_status('  ❌ ESCALATION — run: team status', 31)
                break
            elif unfilled > 0:
                # Restore terminal so the user can type the credentials path
                termios.tcsetattr(stdin_fd, termios.TCSADRAIN, saved_tty)
                sys.stdout.write(
                    f'\r\n\033[33m  ⏸  Credentials needed ({unfilled} unfilled).\r\n'
                    f'     Fill .depend/*.env then press Enter to continue.\033[0m\r\n'
                )
                sys.stdout.flush()
                sys.stdin.readline()
                tty.setraw(stdin_fd)
            else:
                write_status(f'  ↩  Batch {batch_num} complete — starting next batch...', 36)
                time.sleep(1)

    except KeyboardInterrupt:
        pass
    finally:
        try:
            termios.tcsetattr(stdin_fd, termios.TCSADRAIN, saved_tty)
        except Exception:
            pass

if __name__ == '__main__':
    main()
PYEOF

  python3 "$_RUNNER"
}

cmd_scan() {
  if [ ! -d ".pipeline" ]; then
    echo "❌ No .pipeline/ directory found. Run: team init"
    exit 1
  fi

  if [ ! -f ".pipeline/artifacts/component-registry.json" ]; then
    echo "❌ No component registry found. Run the pipeline first to generate component-registry.json"
    exit 1
  fi

  local SCAN_MODE="full"
  case "${1:-}" in
    --refresh)    SCAN_MODE="refresh" ;;
    --check-only) SCAN_MODE="check-only" ;;
    "")           SCAN_MODE="full" ;;
    *)
      echo "Usage: team scan [--refresh|--check-only]"
      exit 1
      ;;
  esac

  echo ""
  echo "  ▶ Duplicate Detector — mode: $SCAN_MODE"
  echo ""

  MODE="$SCAN_MODE" PIPELINE_DIR=".pipeline" \
    bash .pipeline/autosteps/duplicate-detector.sh

  echo ""
}

case "${1:-}" in
  init)    cmd_init ;;
  status)  cmd_status ;;
  upgrade) cmd_upgrade ;;
  version) cmd_version ;;
  update)  cmd_update ;;
  run)     cmd_run ;;
  scan)    cmd_scan "${2:-}" ;;
  replan)  cmd_replan ;;
  *)       usage ;;
esac
TEAM_SCRIPT

chmod +x "$TEAM_CMD"
echo "  ✓ 'team' command installed at $TEAM_CMD"

# ── 4. Install global routing config ──────────────────────────────
echo ""
echo "▶ Step 4 — Global model routing config"

GLOBAL_ROUTING_DIR="$HOME/.config/team-pipeline"
GLOBAL_ROUTING_FILE="$GLOBAL_ROUTING_DIR/routing.json"
mkdir -p "$GLOBAL_ROUTING_DIR"

if [ -f "$GLOBAL_ROUTING_FILE" ]; then
  echo "  ⚠  $GLOBAL_ROUTING_FILE already exists, skipping"
  echo "     To reset: rm $GLOBAL_ROUTING_FILE && bash install.sh"
else
  cp "$REPO_DIR/templates/routing.json" "$GLOBAL_ROUTING_FILE"
  echo "  ✓ $GLOBAL_ROUTING_FILE"
  echo ""
  echo "  To enable model routing globally:"
  echo "    1. Edit $GLOBAL_ROUTING_FILE"
  echo "    2. Set \"enabled\": true"
  echo "    3. Fill in api_key for your provider"
fi

# Copy install.sh itself so `team update` works
cp "$REPO_DIR/install.sh" "$TEMPLATES_DST/install.sh" 2>/dev/null || true

# ── PATH check ──────────────────────────────────────────────────────
echo ""
if echo "$PATH" | grep -q "$BIN_DIR"; then
  echo "  ✓ $BIN_DIR is in PATH"
else
  echo "  ⚠  Add the following to your shell profile (~/.bashrc or ~/.zshrc):"
  echo ""
  echo '     export PATH="$HOME/.local/bin:$PATH"'
  echo ""
  echo "  Then restart your terminal or run: source ~/.bashrc"
fi

# ── Verify agents ────────────────────────────────────────────────────
echo ""
echo "── Verification ────────────────────────────────────────────────"
REQUIRED=(pilot clarifier architect auditor-gate auditor-biz auditor-tech auditor-qa auditor-ops resolver planner contract-formalizer builder-frontend builder-backend builder-dba builder-security builder-infra simplifier inspector tester documenter deployer monitor migrator optimizer translator github-ops)
MISSING=0
for agent in "${REQUIRED[@]}"; do
  if [ ! -f "$AGENTS_DST/$agent.md" ]; then
    echo "  ✗ $agent (missing)"
    MISSING=$((MISSING + 1))
  fi
done

if [ "$MISSING" -eq 0 ]; then
  echo "  ✓ All 26 agents verified"
else
  echo "  ❌ $MISSING agents missing"
  exit 1
fi

# ── Verify & enable required plugins ──────────────────────────────────
echo ""
echo "── Required Plugins ────────────────────────────────────────────"

SETTINGS_FILE="$HOME/.claude/settings.json"
REQUIRED_PLUGINS=("code-review" "code-simplifier")

# Ensure settings.json exists with basic structure
if [ ! -f "$SETTINGS_FILE" ]; then
  mkdir -p "$HOME/.claude"
  echo '{"enabledPlugins":{}}' > "$SETTINGS_FILE"
  echo "  ✓ Created $SETTINGS_FILE"
fi

PLUGINS_CHANGED=false
for plugin in "${REQUIRED_PLUGINS[@]}"; do
  PLUGIN_KEY="${plugin}@claude-plugins-official"
  # Check if plugin is already enabled
  if python3 -c "
import json, sys
s = json.load(open('$SETTINGS_FILE'))
ep = s.get('enabledPlugins', {})
sys.exit(0 if ep.get('$PLUGIN_KEY') == True else 1)
" 2>/dev/null; then
    echo "  ✓ $plugin (enabled)"
  else
    # Enable the plugin
    python3 -c "
import json
s = json.load(open('$SETTINGS_FILE'))
if 'enabledPlugins' not in s:
    s['enabledPlugins'] = {}
s['enabledPlugins']['$PLUGIN_KEY'] = True
with open('$SETTINGS_FILE', 'w') as f:
    json.dump(s, f, indent=2)
" 2>/dev/null
    if [ $? -eq 0 ]; then
      echo "  ✓ $plugin (auto-enabled)"
      PLUGINS_CHANGED=true
    else
      echo "  ⚠  $plugin — failed to enable, please enable manually:"
      echo "     Add '\"$PLUGIN_KEY\": true' to enabledPlugins in $SETTINGS_FILE"
    fi
  fi
done

if [ "$PLUGINS_CHANGED" = true ]; then
  echo ""
  echo "  ℹ  Plugins enabled. Restart Claude Code for changes to take effect."
fi

# ── Done ─────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✅  Installation complete!                          ║"
echo "║                                                      ║"
echo "║  Quick start:                                        ║"
echo "║    cd your-project                                   ║"
echo "║    team init                                         ║"
echo "║    claude --dangerously-skip-permissions --agent pilot  ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
