#!/bin/bash
# install.sh — lfun-team-pipeline installer
# Installs agents, templates, and the `team` CLI command.
#
# Usage:
#   bash install.sh              # normal install
#   bash install.sh --update     # update existing installation

set -euo pipefail

VERSION="6.4"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_SRC="$REPO_DIR/agents"
AGENTS_DST="$HOME/.claude/agents"
TEMPLATES_DST="$HOME/.local/share/team-pipeline"
BIN_DIR="$HOME/.local/bin"
TEAM_CMD="$BIN_DIR/team"

UPDATE_MODE="${1:-}"

print_header() {
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║       lfun-team-pipeline  v${VERSION}  installer        ║"
  echo "║       Claude Code Multi-Agent Delivery Pipeline      ║"
  echo "╚══════════════════════════════════════════════════════╝"
  echo ""
}

print_header

# ── 1. Install agents to ~/.claude/agents/ ──────────────────────────
echo "▶ Step 1/3 — Installing agents to $AGENTS_DST"

if [ ! -d "$AGENTS_SRC" ]; then
  echo "  ❌ agents/ directory not found. Run this script from the repo root."
  exit 1
fi

mkdir -p "$AGENTS_DST"

EXISTING=$(find "$AGENTS_DST" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l)
if [ "$EXISTING" -gt 0 ] && [ "$UPDATE_MODE" != "--update" ]; then
  BACKUP_DIR="$AGENTS_DST.backup.$(date +%Y%m%d%H%M%S)"
  echo "  ⚠  Backing up $EXISTING existing agents → $BACKUP_DIR"
  cp -r "$AGENTS_DST" "$BACKUP_DIR"
fi

INSTALLED=0
while IFS= read -r f; do
  cp "$f" "$AGENTS_DST/$(basename "$f")"
  INSTALLED=$((INSTALLED + 1))
done < <(find "$AGENTS_SRC" -maxdepth 1 -name "*.md" | sort)

echo "  ✓ $INSTALLED agents installed"

# ── 2. Copy templates to ~/.local/share/team-pipeline/ ──────────────
echo ""
echo "▶ Step 2/3 — Installing templates to $TEMPLATES_DST"

mkdir -p "$TEMPLATES_DST"
cp -r "$REPO_DIR/templates/." "$TEMPLATES_DST/"
echo "  ✓ Pipeline templates installed"

# ── 3. Install `team` CLI to ~/.local/bin/ ───────────────────────────
echo ""
echo "▶ Step 3/3 — Installing \`team\` command to $BIN_DIR"

mkdir -p "$BIN_DIR"
cat > "$TEAM_CMD" << 'TEAM_SCRIPT'
#!/bin/bash
# team — lfun-team-pipeline CLI
set -euo pipefail

VERSION="6.4"
TEAM_HOME="$HOME/.local/share/team-pipeline"

usage() {
  echo ""
  echo "  lfun-team-pipeline v${VERSION}"
  echo ""
  echo "  Usage: team <command>"
  echo ""
  echo "  Commands:"
  echo "    init      Initialize pipeline in the current project directory"
  echo "    upgrade   Upgrade playbook + autosteps in-place (preserves state)"
  echo "    version   Print version"
  echo "    replan    Re-plan the proposal queue (keeps completed work)"
  echo "    update    Re-run installer to update agents and templates"
  echo ""
  echo "  Examples:"
  echo "    cd my-project && team init"
  echo "    claude --agent orchestrator"
  echo ""
}

cmd_init() {
  if [ ! -d "$TEAM_HOME/.pipeline" ]; then
    echo "❌ Team pipeline not installed. Run: bash install.sh"
    exit 1
  fi

  echo ""
  echo "  Initializing lfun-team-pipeline in: $(pwd)"
  echo ""

  # Create directory structure
  mkdir -p .pipeline/autosteps .pipeline/artifacts .pipeline/history

  # Copy config
  if [ -f ".pipeline/config.json" ]; then
    echo "  ⚠  .pipeline/config.json already exists, skipping"
  else
    cp "$TEAM_HOME/.pipeline/config.json" .pipeline/config.json
    echo "  ✓ .pipeline/config.json"
  fi

  # Copy playbook
  cp "$TEAM_HOME/.pipeline/playbook.md" .pipeline/playbook.md
  echo "  ✓ .pipeline/playbook.md"

  # Copy project-memory template (only if not exists, preserve user data)
  if [ -f ".pipeline/project-memory.json" ]; then
    echo "  ⚠  .pipeline/project-memory.json already exists, skipping"
  else
    cp "$TEAM_HOME/.pipeline/project-memory.json" .pipeline/project-memory.json
    echo "  ✓ .pipeline/project-memory.json"
  fi

  # Note: proposal-queue.json is NOT copied here.
  # It is generated by System Planning (first run of `claude --agent orchestrator`).
  # Copying an empty template would bypass System Planning and cause immediate ALL-COMPLETED.

  # Copy autosteps
  STEP_COUNT=0
  while IFS= read -r f; do
    dest=".pipeline/autosteps/$(basename "$f")"
    cp "$f" "$dest"
    STEP_COUNT=$((STEP_COUNT + 1))
  done < <(find "$TEAM_HOME/.pipeline/autosteps" -name "*.sh" | sort)
  echo "  ✓ .pipeline/autosteps/ ($STEP_COUNT scripts)"

  # Copy CLAUDE.md
  if [ -f "CLAUDE.md" ]; then
    echo "  ⚠  CLAUDE.md already exists, skipping"
  else
    cp "$TEAM_HOME/CLAUDE.md" CLAUDE.md
    echo "  ✓ CLAUDE.md"
  fi

  echo ""
  echo "  ✅ Pipeline initialized! Next steps:"
  echo ""
  echo "     1. Edit .pipeline/config.json  ← set project_name and tech stack"
  echo "     2. claude --agent orchestrator ← start the pipeline"
  echo ""
}

cmd_version() {
  echo "lfun-team-pipeline v${VERSION}"
}

cmd_update() {
  echo ""
  echo "  To update, run install.sh from the team-creator git repository:"
  echo ""
  echo "    cd /path/to/team-creator && bash install.sh --update"
  echo ""
  echo "  This ensures agents and templates are copied from the latest source."
  echo ""
}

cmd_upgrade() {
  if [ ! -d "$TEAM_HOME/.pipeline" ]; then
    echo "❌ Team pipeline not installed. Run: bash install.sh"
    exit 1
  fi

  if [ ! -d ".pipeline" ]; then
    echo "❌ No .pipeline/ directory found. Run: team init"
    exit 1
  fi

  echo ""
  echo "  Upgrading lfun-team-pipeline in: $(pwd)"
  echo ""

  # Upgrade playbook (always overwrite)
  cp "$TEAM_HOME/.pipeline/playbook.md" .pipeline/playbook.md
  echo "  ✓ .pipeline/playbook.md upgraded"

  # Upgrade autosteps (always overwrite)
  cp "$TEAM_HOME/.pipeline/autosteps/"*.sh .pipeline/autosteps/
  AUTOSTEP_COUNT=$(ls .pipeline/autosteps/*.sh 2>/dev/null | wc -l)
  echo "  ✓ $AUTOSTEP_COUNT autosteps upgraded"

  # Upgrade CLAUDE.md (always overwrite)
  if [ -f "$TEAM_HOME/CLAUDE.md" ]; then
    cp "$TEAM_HOME/CLAUDE.md" CLAUDE.md
    echo "  ✓ CLAUDE.md upgraded"
  fi

  # Preserved files (not touched):
  echo ""
  echo "  Preserved (not modified):"
  echo "    .pipeline/config.json"
  echo "    .pipeline/state.json"
  echo "    .pipeline/project-memory.json"
  echo "    .pipeline/proposal-queue.json"
  echo "    .pipeline/artifacts/*"
  echo ""

  # Show version
  echo "  Upgraded to v${VERSION}"

  # Add execution_log to state.json if missing
  if [ -f ".pipeline/state.json" ]; then
    python3 -c "
import json
s = json.load(open('.pipeline/state.json'))
changed = False
if 'execution_log' not in s:
    s['execution_log'] = []
    changed = True
if changed:
    json.dump(s, open('.pipeline/state.json', 'w'), ensure_ascii=False, indent=2)
    print('  ✓ state.json: added execution_log field')
else:
    print('  ✓ state.json: already compatible')
" 2>/dev/null || true
  fi

  echo ""
  echo "  Run 'claude --agent orchestrator' to continue from current phase."
  echo ""
}

cmd_replan() {
  if [ ! -f ".pipeline/proposal-queue.json" ]; then
    echo "❌ No proposal queue found. Run: claude --agent orchestrator"
    exit 1
  fi

  echo ""
  echo "  Re-planning: removing proposal queue to trigger System Planning"
  echo ""

  # Archive current queue
  BACKUP="proposal-queue.backup.$(date +%Y%m%d%H%M%S).json"
  cp .pipeline/proposal-queue.json ".pipeline/$BACKUP" 2>/dev/null || true
  echo "  ✓ Backed up current queue to .pipeline/$BACKUP"

  # Remove queue to trigger re-planning
  rm .pipeline/proposal-queue.json
  echo "  ✓ Queue removed. Next 'claude --agent orchestrator' will enter System Planning."
  echo ""
  echo "  Note: Completed proposals are preserved in project-memory.json."
  echo "  The new plan will build on existing progress."
  echo ""
}

case "${1:-}" in
  init)    cmd_init ;;
  upgrade) cmd_upgrade ;;
  version) cmd_version ;;
  update)  cmd_update ;;
  replan)  cmd_replan ;;
  *)       usage ;;
esac
TEAM_SCRIPT

chmod +x "$TEAM_CMD"
echo "  ✓ 'team' command installed at $TEAM_CMD"

# Copy install.sh itself so `team update` works
cp "$REPO_DIR/install.sh" "$TEMPLATES_DST/install.sh" 2>/dev/null || true

# ── PATH check ──────────────────────────────────────────────────────
echo ""
if echo "$PATH" | grep -q "$BIN_DIR"; then
  echo "  ✓ $BIN_DIR is in PATH"
else
  echo "  ⚠  Add the following to your shell profile (~/.bashrc or ~/.zshrc):"
  echo ""
  echo '     export PATH="$HOME/.local/bin:$PATH"'
  echo ""
  echo "  Then restart your terminal or run: source ~/.bashrc"
fi

# ── Verify agents ────────────────────────────────────────────────────
echo ""
echo "── Verification ────────────────────────────────────────────────"
REQUIRED=(orchestrator clarifier architect auditor-gate auditor-biz auditor-tech auditor-qa auditor-ops resolver planner contract-formalizer builder-frontend builder-backend builder-dba builder-security builder-infra simplifier inspector tester documenter deployer monitor migrator optimizer translator github-ops)
MISSING=0
for agent in "${REQUIRED[@]}"; do
  if [ ! -f "$AGENTS_DST/$agent.md" ]; then
    echo "  ✗ $agent (missing)"
    MISSING=$((MISSING + 1))
  fi
done

if [ "$MISSING" -eq 0 ]; then
  echo "  ✓ All 26 agents verified"
else
  echo "  ❌ $MISSING agents missing"
  exit 1
fi

# ── Done ─────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✅  Installation complete!                          ║"
echo "║                                                      ║"
echo "║  Quick start:                                        ║"
echo "║    cd your-project                                   ║"
echo "║    team init                                         ║"
echo "║    claude --agent orchestrator                       ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
