#!/bin/bash
# install.sh — lfun-team-pipeline installer
# Installs agents, templates, and the `team` CLI command.
#
# Usage:
#   bash install.sh              # normal install
#   bash install.sh --update     # update existing installation

set -euo pipefail

VERSION="6.4"
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_SRC="$REPO_DIR/agents"
AGENTS_DST="$HOME/.claude/agents"
TEMPLATES_DST="$HOME/.local/share/team-pipeline"
BIN_DIR="$HOME/.local/bin"
TEAM_CMD="$BIN_DIR/team"

UPDATE_MODE="${1:-}"

print_header() {
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║       lfun-team-pipeline  v${VERSION}  installer        ║"
  echo "║       Claude Code Multi-Agent Delivery Pipeline      ║"
  echo "╚══════════════════════════════════════════════════════╝"
  echo ""
}

print_header

# ── 1. Install agents to ~/.claude/agents/ ──────────────────────────
echo "▶ Step 1/3 — Installing agents to $AGENTS_DST"

if [ ! -d "$AGENTS_SRC" ]; then
  echo "  ❌ agents/ directory not found. Run this script from the repo root."
  exit 1
fi

mkdir -p "$AGENTS_DST"

EXISTING=$(find "$AGENTS_DST" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l)
if [ "$EXISTING" -gt 0 ] && [ "$UPDATE_MODE" != "--update" ]; then
  BACKUP_DIR="$AGENTS_DST.backup.$(date +%Y%m%d%H%M%S)"
  echo "  ⚠  Backing up $EXISTING existing agents → $BACKUP_DIR"
  cp -r "$AGENTS_DST" "$BACKUP_DIR"
fi

INSTALLED=0
while IFS= read -r f; do
  cp "$f" "$AGENTS_DST/$(basename "$f")"
  INSTALLED=$((INSTALLED + 1))
done < <(find "$AGENTS_SRC" -maxdepth 1 -name "*.md" | sort)

echo "  ✓ $INSTALLED agents installed"

# ── 2. Copy templates to ~/.local/share/team-pipeline/ ──────────────
echo ""
echo "▶ Step 2/3 — Installing templates to $TEMPLATES_DST"

mkdir -p "$TEMPLATES_DST"
cp -r "$REPO_DIR/templates/." "$TEMPLATES_DST/"
echo "  ✓ Pipeline templates installed"

# ── 3. Install `team` CLI to ~/.local/bin/ ───────────────────────────
echo ""
echo "▶ Step 3/3 — Installing \`team\` command to $BIN_DIR"

mkdir -p "$BIN_DIR"
cat > "$TEAM_CMD" << 'TEAM_SCRIPT'
#!/bin/bash
# team — lfun-team-pipeline CLI
set -euo pipefail

VERSION="6.4"
TEAM_HOME="$HOME/.local/share/team-pipeline"

usage() {
  echo ""
  echo "  lfun-team-pipeline v${VERSION}"
  echo ""
  echo "  Usage: team <command>"
  echo ""
  echo "  Commands:"
  echo "    init      Initialize pipeline in the current project directory"
  echo "    status    Show current pipeline execution progress"
  echo "    upgrade   Upgrade playbook + autosteps in-place (preserves state)"
  echo "    version   Print version"
  echo "    replan    Re-plan the proposal queue (keeps completed work)"
  echo "    run       Auto-run pipeline batches until done or intervention needed"
  echo "    update    Re-run installer to update agents and templates"
  echo ""
  echo "  Examples:"
  echo "    cd my-project && team init"
  echo "    team run"
  echo "    team status"
  echo ""
}

cmd_init() {
  if [ ! -d "$TEAM_HOME/.pipeline" ]; then
    echo "❌ Team pipeline not installed. Run: bash install.sh"
    exit 1
  fi

  echo ""
  echo "  Initializing lfun-team-pipeline in: $(pwd)"
  echo ""

  # Create directory structure
  mkdir -p .pipeline/autosteps .pipeline/artifacts .pipeline/history

  # Copy config
  if [ -f ".pipeline/config.json" ]; then
    echo "  ⚠  .pipeline/config.json already exists, skipping"
  else
    cp "$TEAM_HOME/.pipeline/config.json" .pipeline/config.json
    echo "  ✓ .pipeline/config.json"
  fi

  # Copy playbook
  cp "$TEAM_HOME/.pipeline/playbook.md" .pipeline/playbook.md
  echo "  ✓ .pipeline/playbook.md"

  # Copy project-memory template (only if not exists, preserve user data)
  if [ -f ".pipeline/project-memory.json" ]; then
    echo "  ⚠  .pipeline/project-memory.json already exists, skipping"
  else
    cp "$TEAM_HOME/.pipeline/project-memory.json" .pipeline/project-memory.json
    echo "  ✓ .pipeline/project-memory.json"
  fi

  # Note: proposal-queue.json is NOT copied here.
  # It is generated by System Planning (first run of `claude --agent orchestrator`).
  # Copying an empty template would bypass System Planning and cause immediate ALL-COMPLETED.

  # Copy autosteps
  STEP_COUNT=0
  while IFS= read -r f; do
    dest=".pipeline/autosteps/$(basename "$f")"
    cp "$f" "$dest"
    STEP_COUNT=$((STEP_COUNT + 1))
  done < <(find "$TEAM_HOME/.pipeline/autosteps" -name "*.sh" | sort)
  echo "  ✓ .pipeline/autosteps/ ($STEP_COUNT scripts)"

  # Copy CLAUDE.md
  if [ -f "CLAUDE.md" ]; then
    echo "  ⚠  CLAUDE.md already exists, skipping"
  else
    cp "$TEAM_HOME/CLAUDE.md" CLAUDE.md
    echo "  ✓ CLAUDE.md"
  fi

  echo ""
  echo "  ✅ Pipeline initialized! Next steps:"
  echo ""
  echo "     1. Edit .pipeline/config.json  ← set project_name and tech stack"
  echo "     2. claude --dangerously-skip-permissions --agent orchestrator ← start the pipeline"
  echo ""
}

cmd_version() {
  echo "lfun-team-pipeline v${VERSION}"
}

cmd_update() {
  echo ""
  echo "  To update, run install.sh from the team-creator git repository:"
  echo ""
  echo "    cd /path/to/team-creator && bash install.sh --update"
  echo ""
  echo "  This ensures agents and templates are copied from the latest source."
  echo ""
}

cmd_upgrade() {
  if [ ! -d "$TEAM_HOME/.pipeline" ]; then
    echo "❌ Team pipeline not installed. Run: bash install.sh"
    exit 1
  fi

  if [ ! -d ".pipeline" ]; then
    echo "❌ No .pipeline/ directory found. Run: team init"
    exit 1
  fi

  echo ""
  echo "  Upgrading lfun-team-pipeline in: $(pwd)"
  echo ""

  # Upgrade playbook (always overwrite)
  cp "$TEAM_HOME/.pipeline/playbook.md" .pipeline/playbook.md
  echo "  ✓ .pipeline/playbook.md upgraded"

  # Upgrade autosteps (always overwrite)
  cp "$TEAM_HOME/.pipeline/autosteps/"*.sh .pipeline/autosteps/
  AUTOSTEP_COUNT=$(ls .pipeline/autosteps/*.sh 2>/dev/null | wc -l)
  echo "  ✓ $AUTOSTEP_COUNT autosteps upgraded"

  # Upgrade CLAUDE.md (always overwrite)
  if [ -f "$TEAM_HOME/CLAUDE.md" ]; then
    cp "$TEAM_HOME/CLAUDE.md" CLAUDE.md
    echo "  ✓ CLAUDE.md upgraded"
  fi

  # Preserved files (not touched):
  echo ""
  echo "  Preserved (not modified):"
  echo "    .pipeline/config.json"
  echo "    .pipeline/state.json"
  echo "    .pipeline/project-memory.json"
  echo "    .pipeline/proposal-queue.json"
  echo "    .pipeline/artifacts/*"
  echo ""

  # Show version
  echo "  Upgraded to v${VERSION}"

  # Add execution_log to state.json if missing
  if [ -f ".pipeline/state.json" ]; then
    python3 -c "
import json
s = json.load(open('.pipeline/state.json'))
changed = False
if 'execution_log' not in s:
    s['execution_log'] = []
    changed = True
if changed:
    json.dump(s, open('.pipeline/state.json', 'w'), ensure_ascii=False, indent=2)
    print('  ✓ state.json: added execution_log field')
else:
    print('  ✓ state.json: already compatible')
" 2>/dev/null || true
  fi

  echo ""
  echo "  Run 'claude --dangerously-skip-permissions --agent orchestrator' to continue from current phase."
  echo ""
}

cmd_replan() {
  if [ ! -f ".pipeline/proposal-queue.json" ]; then
    echo "❌ No proposal queue found. Run: claude --agent orchestrator"
    exit 1
  fi

  echo ""
  echo "  Re-planning: removing proposal queue to trigger System Planning"
  echo ""

  # Archive current queue
  BACKUP="proposal-queue.backup.$(date +%Y%m%d%H%M%S).json"
  cp .pipeline/proposal-queue.json ".pipeline/$BACKUP" 2>/dev/null || true
  echo "  ✓ Backed up current queue to .pipeline/$BACKUP"

  # Remove queue to trigger re-planning
  rm .pipeline/proposal-queue.json
  echo "  ✓ Queue removed. Next 'claude --agent orchestrator' will enter System Planning."
  echo ""
  echo "  Note: Completed proposals are preserved in project-memory.json."
  echo "  The new plan will build on existing progress."
  echo ""
}

cmd_status() {
  if [ ! -f ".pipeline/state.json" ]; then
    echo ""
    echo "  ❌ No pipeline found in current directory."
    echo "     Run: team init && claude --dangerously-skip-permissions --agent orchestrator"
    echo ""
    exit 1
  fi

  python3 - << 'PYEOF'
import json, os, sys
from datetime import datetime, timezone

# ── ANSI colors ────────────────────────────────────────────────────
RESET  = "\033[0m"
BOLD   = "\033[1m"
DIM    = "\033[2m"
GREEN  = "\033[32m"
YELLOW = "\033[33m"
RED    = "\033[31m"
CYAN   = "\033[36m"
BLUE   = "\033[34m"
WHITE  = "\033[37m"

def c(color, text): return f"{color}{text}{RESET}"

# ── Load state.json ────────────────────────────────────────────────
state = json.load(open(".pipeline/state.json"))
project   = state.get("project_name", os.path.basename(os.getcwd()))
phase     = state.get("current_phase", "?")
last_done = state.get("last_completed_phase", "-")
status    = state.get("status", "?")
pipeline_id = state.get("pipeline_id", "-")
cond      = state.get("conditional_agents", {})
attempts  = state.get("attempt_counts", {})

# ── Header ─────────────────────────────────────────────────────────
print()
print(c(BOLD + CYAN, f"  ╔══ Pipeline Status — {project} ══"))
print(c(CYAN,         f"  ║"))

status_color = GREEN if status == "completed" else (YELLOW if status == "running" else RED)
print(c(CYAN, "  ║") + f"  {c(BOLD, 'Pipeline:')}  {pipeline_id}")
print(c(CYAN, "  ║") + f"  {c(BOLD, 'Status:')}    {c(status_color + BOLD, status.upper())}")
print(c(CYAN, "  ║") + f"  {c(BOLD, 'Phase:')}     {c(BOLD, phase)}  {c(DIM, f'(last done: {last_done})')}")

# ── Conditional agents ─────────────────────────────────────────────
if cond:
    active = [k for k, v in cond.items() if v]
    inactive = [k for k, v in cond.items() if not v]
    parts = [c(GREEN, f"+{k}") for k in active] + [c(DIM, f"-{k}") for k in inactive]
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Agents:')}    {', '.join(parts)}")

# ── Proposal queue ─────────────────────────────────────────────────
queue_file = ".pipeline/proposal-queue.json"
if os.path.exists(queue_file):
    q = json.load(open(queue_file))
    proposals = q.get("proposals", [])
    system_name = q.get("system_name", "")
    total = len(proposals)
    done  = sum(1 for p in proposals if p.get("status") == "completed")
    running = [p for p in proposals if p.get("status") == "running"]

    print(c(CYAN, "  ║"))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'System:')}    {system_name}")
    bar_filled = int(done / total * 20) if total else 0
    bar = c(GREEN, "█" * bar_filled) + c(DIM, "░" * (20 - bar_filled))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Proposals:')} [{bar}{RESET}] {c(BOLD, str(done))}/{total}")
    print(c(CYAN, "  ║"))

    for p in proposals:
        pid    = p.get("id", "?")
        title  = p.get("title", "")
        pst    = p.get("status", "pending")
        if pst == "completed":
            icon = c(GREEN, "✓")
            color = DIM
        elif pst == "running":
            icon = c(YELLOW + BOLD, "▶")
            color = BOLD
        else:
            icon = c(DIM, "○")
            color = ""
        deps = p.get("depends_on", [])
        dep_str = c(DIM, f"  ← {', '.join(deps)}") if deps else ""
        print(c(CYAN, "  ║") + f"    {icon} {c(color, f'[{pid}] {title}')}{dep_str}")

# ── Step execution log ─────────────────────────────────────────────
index_file = ".pipeline/artifacts/logs/pipeline.index.json"
ex_log = state.get("execution_log", [])

steps = []
if os.path.exists(index_file):
    idx = json.load(open(index_file))
    steps = idx.get("steps", [])
elif ex_log:
    steps = ex_log

if steps:
    print(c(CYAN, "  ║"))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Execution Log:')}  ({len(steps)} steps)")

    RESULT_COLOR = {"PASS": GREEN, "WARN": YELLOW, "FAIL": RED, "SKIP": DIM, "ERROR": RED}

    # Show all steps; mark rollbacks
    for i, s in enumerate(steps):
        step   = s.get("step", "?")
        result = s.get("result", "?")
        attempt = s.get("attempt", 1)
        rollback_to = s.get("caused_rollback_to") or s.get("rollback_to")
        triggered_by = s.get("rollback_triggered_by")

        rc = RESULT_COLOR.get(result, WHITE)
        attempt_str = c(DIM, f" ×{attempt}") if attempt > 1 else ""
        rollback_str = c(YELLOW, f" → rollback to {rollback_to}") if rollback_to else ""
        triggered_str = c(DIM, f" [by {triggered_by}]") if triggered_by else ""

        is_last = (i == len(steps) - 1)
        prefix = c(CYAN, "  ║") + ("  └─" if is_last else "  ├─")
        print(f"{prefix} {c(rc + BOLD, result):>6}  {step}{attempt_str}{rollback_str}{triggered_str}")

# ── Retry counts (phases with >1 attempts) ─────────────────────────
notable = {k: v for k, v in attempts.items() if isinstance(v, int) and v > 1}
if notable:
    print(c(CYAN, "  ║"))
    print(c(CYAN, "  ║") + f"  {c(BOLD, 'Retried phases:')}")
    for k, v in sorted(notable.items()):
        print(c(CYAN, "  ║") + f"    {c(YELLOW, k)}: {v} attempts")

# ── Footer ─────────────────────────────────────────────────────────
print(c(CYAN, "  ║"))
print(c(BOLD + CYAN, "  ╚" + "═" * 40))
print()
PYEOF
}

cmd_run() {
  if [ ! -d ".pipeline" ]; then
    echo "❌ No .pipeline/ directory found. Run: team init"
    exit 1
  fi

  echo ""
  echo "  lfun-team-pipeline — Autonomous Run"
  echo "  ─────────────────────────────────────────────────────"
  echo "  Batches run automatically. Stops on: completion,"
  echo "  escalation, or credentials needed. Press Ctrl+C to abort."
  echo ""

  BATCH=0
  while true; do
    BATCH=$((BATCH + 1))
    TIMESTAMP=$(date "+%H:%M:%S")
    echo "  [$TIMESTAMP] ── Batch #$BATCH ───────────────────────────────"
    echo ""

    # Run orchestrator in non-interactive mode (-p); exits automatically after one batch
    # Unset CLAUDECODE to allow nested claude invocation (e.g. when run from within Claude Code)
    set +e
    env -u CLAUDECODE claude --dangerously-skip-permissions --agent orchestrator -p "请执行下一批次"
    CLAUDE_EXIT=$?
    set -e

    echo ""
    echo "  ─────────────────────────────────────────────────────"

    # state.json must exist after each run
    if [ ! -f ".pipeline/state.json" ]; then
      echo "  ⚠  state.json not found. Run 'team init' first."
      exit 1
    fi

    # Parse state via python3
    PARSED=$(python3 - << 'PYEOF2'
import json, sys
try:
    s = json.load(open(".pipeline/state.json"))
    status = s.get("status", "running")
    phase  = s.get("current_phase", "?")
    dep    = s.get("depend_collector_result", {})
    unfilled = len(dep.get("unfilled_deps", []))
    print(f"{status}|{phase}|{unfilled}")
except Exception as e:
    print(f"error|?|0")
PYEOF2
)

    STATUS=$(echo "$PARSED" | cut -d'|' -f1)
    PHASE=$(echo "$PARSED"  | cut -d'|' -f2)
    UNFILLED=$(echo "$PARSED" | cut -d'|' -f3)

    if [ "$STATUS" = "ALL-COMPLETED" ]; then
      echo "  ✅ All proposals completed! Pipeline finished."
      echo ""
      break
    fi

    if [ "$STATUS" = "escalation" ]; then
      echo "  ❌ ESCALATION — manual intervention required."
      echo "     Run: team status"
      echo ""
      exit 1
    fi

    if [ "${UNFILLED:-0}" -gt "0" ]; then
      echo "  ⏸  Credentials needed ($UNFILLED unfilled dependency)."
      echo "     1. Fill in the .depend/*.env files"
      echo "     2. Then resume: team run"
      echo ""
      exit 0
    fi

    if [ "$CLAUDE_EXIT" -ne 0 ]; then
      echo "  ⚠  claude exited with code $CLAUDE_EXIT (phase: $PHASE)."
      echo "     Check output above. Resume: team run"
      echo ""
      exit 1
    fi

    echo "  ✓ Batch #$BATCH done (phase: $PHASE) — continuing..."
    sleep 1
    echo ""
  done
}

case "${1:-}" in
  init)    cmd_init ;;
  status)  cmd_status ;;
  upgrade) cmd_upgrade ;;
  version) cmd_version ;;
  update)  cmd_update ;;
  run)     cmd_run ;;
  replan)  cmd_replan ;;
  *)       usage ;;
esac
TEAM_SCRIPT

chmod +x "$TEAM_CMD"
echo "  ✓ 'team' command installed at $TEAM_CMD"

# Copy install.sh itself so `team update` works
cp "$REPO_DIR/install.sh" "$TEMPLATES_DST/install.sh" 2>/dev/null || true

# ── PATH check ──────────────────────────────────────────────────────
echo ""
if echo "$PATH" | grep -q "$BIN_DIR"; then
  echo "  ✓ $BIN_DIR is in PATH"
else
  echo "  ⚠  Add the following to your shell profile (~/.bashrc or ~/.zshrc):"
  echo ""
  echo '     export PATH="$HOME/.local/bin:$PATH"'
  echo ""
  echo "  Then restart your terminal or run: source ~/.bashrc"
fi

# ── Verify agents ────────────────────────────────────────────────────
echo ""
echo "── Verification ────────────────────────────────────────────────"
REQUIRED=(orchestrator clarifier architect auditor-gate auditor-biz auditor-tech auditor-qa auditor-ops resolver planner contract-formalizer builder-frontend builder-backend builder-dba builder-security builder-infra simplifier inspector tester documenter deployer monitor migrator optimizer translator github-ops)
MISSING=0
for agent in "${REQUIRED[@]}"; do
  if [ ! -f "$AGENTS_DST/$agent.md" ]; then
    echo "  ✗ $agent (missing)"
    MISSING=$((MISSING + 1))
  fi
done

if [ "$MISSING" -eq 0 ]; then
  echo "  ✓ All 26 agents verified"
else
  echo "  ❌ $MISSING agents missing"
  exit 1
fi

# ── Done ─────────────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ✅  Installation complete!                          ║"
echo "║                                                      ║"
echo "║  Quick start:                                        ║"
echo "║    cd your-project                                   ║"
echo "║    team init                                         ║"
echo "║    claude --dangerously-skip-permissions --agent orchestrator  ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
